Issue/3376
Usabi/consul_gva pull request #4
Opened 2020-11-04 18:44 UTC by AleVeraM

## References

> Related Issues/Pull Requests/Travis Builds/Rollbar errors/etc...

## Objectives

> Implement custom census_api

## Visual Changes

> Any visual changes? please attach screenshots (or gifs) showing them.
> If modified views are public (not the admin panel), try them in mobile display (with your browser's developer console) and add screenshots.

## Notes

> Mention rake tasks or actions to be done when deploying this changes to a server (if any).
> Explain any caveats, or important things to notice like deprecations (if any).

2020-11-09 16:34 UTC, ialiendeg commented on lib/custom/census_api.rb
> +      Rails.application.secrets.census_api_end_point.present?
Dejaste este método aunque es igual que en el original. Aún así, yo lo dejaría pero no usaría `c ensus_api_end_point` para el path y luego `census_api_age_validator` y `census_api_residence_validator`, sino que sólo usaría los dos últimos con path/fichero y en el método comprobaría que están presentes los valores de las dos claves. También tendrías que cambiar donde llamas a los php. Lo que hablamos, esto realmente ya no es un endpoint, así que la clave existente de antes creo que realmente nos sobra.

2020-11-09 16:36 UTC, ialiendeg commented on lib/custom/census_api.rb
> +      (Rails.env.development? || Rails.env.staging? || Rails.env.preproduction? || Rails.env.production?) && end_point_defined?
Añadir aquí el chequeo de development no lo solemos subir, nos lo cambiamos en local para hacer pruebas con fuego real, pero en el repo se supone que sólo se puede usar el censo en los demás entornos.

2020-11-09 16:40 UTC, ialiendeg requested changes
Hice un par de pruebas en local y parece funcionar, aunque tuve que mirar que habías usado el secret existente como path. Mira el comentario más abajo.

2020-11-16 14:52 UTC, LauraConcepcion approved these changes

2020-11-16 14:53 UTC, merged